services:
  postgres:
    hostname: postgres
    image: postgres:14.9-alpine
    networks:
      - external_network
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_CONTAINER_EXPOSED_PORT}:${POSTGRES_CONTAINER_INTERNAL_PORT}
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - external_network
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      BOMBARDIER_SERVER_IP: host.docker.internal:1234
      SPRING_DATASOURCE_HIKARI_JDBC_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_HIKARI_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_HIKARI_PASSWORD: ${POSTGRES_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  external_network:
    driver: bridge